environment:

  matrix:
    - MSYS: "C:\\msys64\\mingw32.exe"

branches:
  only:
    - master

clone_depth: 1

# init:
#   - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:

  - ps: |
      function bash($command) {
        Write-Host $command -NoNewline
        cmd /c start /wait C:\msys64\usr\bin\sh.exe --login -c $command
        Write-Host " - OK" -ForegroundColor Green
      }

      bash 'pacman -Sy --noconfirm git'
      bash 'git clone https://dev.gajim.org/lovetox/gajim.git'

  - cmd: '%MSYS% C:/msys64/home/appveyor/gajim/win/build.sh'
  # Ugly workaround, because i found no way to tell when mingw32.exe returns
  - cmd: timeout 900

  # Push Installer Exe
  - ps: $env:TIME_STRING=(get-date -UFormat "%Y-%m-%d").ToString()
  - ps: $env:BUILDROOT="C:\msys64\home\appveyor\gajim\win\_build_root"
  - ps: Push-AppveyorArtifact "$($env:BUILDROOT)/Gajim.exe" -FileName "Gajim-Master-$($env:TIME_STRING).exe"
  - ps: Push-AppveyorArtifact "$($env:BUILDROOT)/Gajim-Portable.exe" -FileName "Gajim-Portable-Master-$($env:TIME_STRING).exe"

build: off

# on_finish:
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

deploy:
    # FTP deployment provider settings
  - provider: FTP
    protocol: ftp
    host: panoramix.gajim.org
    username:
      secure: SNcOJDhUtBjfddbKXudE2w==
    password:
      secure: tQkYbcUb6nChCp0cdqo4CA==
    folder: win_snap
    active_mode: false
    beta: true      # enable alternative FTP library for 'ftp' and 'ftps' modes
    debug: true
